const jueguitos = [
    {
        "id":0,
        "nombre": "Fortnite: Salvar el Mundo",
        "genero":"Looter Shooter, Aventura, Defensa de Torres",
        "desarrollador":"Epic Games",
        "plataformas":"PC, PS4, PS5, Xbox One, Xbox Series X/S",
        "precio": "$12.000",
        "foto":"https://i.ibb.co/KKjnD02/fortnite-stw.png",
    },
    {
        "id":1,
        "nombre": "La Leyenda de Pipi",
        "genero":"Aventura, Hack & Slash",
        "desarrollador":"C-Force",
        "plataformas":"PC, PS4, PS5, Xbox One, Xbox Series X/S, Nintendo Switch",
        "precio": "$1.000.000",
        "foto":"https://i.ibb.co/vJr7ztb/pipi.png",
    },
    {
        "id":2,
        "nombre": "Dante's Inferno",
        "genero":"Acción, Hack & Slash",
        "desarrollador":"Visceral Games, Electronic Arts",
        "plataformas":"PS3, PSP, Xbox 360",
        "precio": "$15.000",
        "foto":"https://i.ibb.co/cFd9Gp3/dantes-inferno.png",
    },
    {
        "id":3,
        "nombre": "One Piece: World Seeker",
        "genero":"Pelea, Acción",
        "desarrollador":"Ganbarion",
        "plataformas":"PS4, Xbox One, PC",
        "precio": "$40.000",
        "foto":"https://i.ibb.co/DKpPvMT/one-piece.png",
    },
    {
        "id":4,
        "nombre": "HELLDIVERS 2",
        "genero":"Disparos, Acción",
        "desarrollador":"Arrowhead Game Studios",
        "plataformas":"PS5, PC",
        "precio": "$20.000",
        "foto":"https://i.ibb.co/6bws3SG/helldivers2.png",
    },
    {
        "id":5,
        "nombre": "Minecraft Java",
        "genero":"Aventura, Exploración, Mundo Abierto",
        "desarrollador":"Mojang Studios",
        "plataformas":"PC",
        "precio": "$25.000",
        "foto":"https://i.ibb.co/0ZG2z6L/minecraft.png",
    },
    {
        "id":6,
        "nombre": "Grand Theft Auto 5",
        "genero":"Disparos, Exploración, Mundo Abierto",
        "desarrollador":"Rockstar Games, Rockstar North",
        "plataformas":"PC, PS3, Xbox 360, PS4, Xbox One, PS5, Xbox Series X/S",
        "precio": "$30.000",
        "foto":"https://i.ibb.co/bF71QRj/GTA5.png",
    },
    {
        "id":7,
        "nombre": "Deep Rock Galactic",
        "genero":"Aventura, Exploración, Disparos",
        "desarrollador":"Ghost Ship Games",
        "plataformas":"PC, PS5, PS4, Xbox One, Xbox Series X/S",
        "precio": "$15.000",
        "foto":"https://i.ibb.co/jbSckNh/drg.png",
    },
    {
        "id":8,
        "nombre": "POSTAL 2",
        "genero":"Disparos, Exploración, Mundo Abierto",
        "desarrollador":"Running with Scissors",
        "plataformas":"PC",
        "precio": "$5.000",
        "foto":"https://i.ibb.co/2Wyzn5b/postal-2.png",
    },
    {
        "id":9,
        "nombre": "Portal 2",
        "genero":"Disparos, Exploración, Mundo Abierto",
        "desarrollador":"Valve",
        "plataformas":"PC, PS3, Xbox 360, Nintendo Switch",
        "precio": "$10.000",
        "foto":"https://i.ibb.co/HGHbF0n/portal-2.png",
    },
    {
        "id":10,
        "nombre": "Lethal Company",
        "genero":"Terror, Aventura",
        "desarrollador":"Zeekerss",
        "plataformas":"PC",
        "precio": "$10.000",
        "foto":"https://i.ibb.co/VCLwjXz/lethal-company.png",
    },
    {
        "id":11,
        "nombre": "Content Warning",
        "genero":"Terror, Aventura",
        "desarrollador":"Landfall Games",
        "plataformas":"PC",
        "precio": "$10.000",
        "foto":"https://i.ibb.co/VCLwjXz/lethal-company.png",
    },
    {
        "id":12,
        "nombre": "Fire Emblem: Three Houses",
        "genero":"RPG Táctico",
        "desarrollador":"Intelligent Systems",
        "plataformas":"Nintendo Switch",
        "precio": "$25.000",
        "foto":"https://i.ibb.co/VCLwjXz/lethal-company.png",
    },
    {
        "id":13,
        "nombre": "Fallout 4",
        "genero":"RPG de Acción, Disparos",
        "desarrollador":"Bethesda",
        "plataformas":"PC, PS4, PS5, Xbox One, Xbox Series X/S",
        "precio": "$30.000",
        "foto":"https://i.ibb.co/VCLwjXz/lethal-company.png",
    },
    {
        "id":14,
        "nombre": "Borderlands 2",
        "genero":"RPG de Acción, Disparos",
        "desarrollador":"Gearbox Software",
        "plataformas":"PC, PS3, PS4, Xbox 360, Xbox One, PSVita",
        "precio": "$15.000",
        "foto":"https://i.ibb.co/VCLwjXz/lethal-company.png",
    }
];

module.exports = { jueguitos };