const jueguitos = [
    {
        "id":0,
        "nombre": "Fortnite: Salvar el Mundo",
        "genero":"Looter Shooter, Aventura, Defensa de Torres",
        "desarrollador":"Epic Games",
        "plataformas":"PC, PS4, PS5, Xbox One, Xbox Series X/S",
        "precio": 12000,
        "foto":"https://i.ibb.co/KKjnD02/fortnite-stw.png",
    },
    {
        "id":1,
        "nombre": "La Leyenda de Pipi",
        "genero":"Aventura, Hack & Slash",
        "desarrollador":"C-Force",
        "plataformas":"PC, PS4, PS5, Xbox One, Xbox Series X/S, Nintendo Switch",
        "precio": 1000000,
        "foto":"https://i.ibb.co/vJr7ztb/pipi.png",
    },
    {
        "id":2,
        "nombre": "Dante's Inferno",
        "genero":"Acción, Hack & Slash",
        "desarrollador":"Visceral Games, Electronic Arts",
        "plataformas":"PS3, PSP, Xbox 360",
        "precio": 15000,
        "foto":"https://i.ibb.co/cFd9Gp3/dantes-inferno.png",
    },
    {
        "id":3,
        "nombre": "One Piece: World Seeker",
        "genero":"Pelea, Acción",
        "desarrollador":"Ganbarion",
        "plataformas":"PS4, Xbox One, PC",
        "precio": 40000,
        "foto":"https://i.ibb.co/DKpPvMT/one-piece.png",
    },
    {
        "id":4,
        "nombre": "HELLDIVERS 2",
        "genero":"Disparos, Acción",
        "desarrollador":"Arrowhead Game Studios",
        "plataformas":"PS5, PC",
        "precio": 20000,
        "foto":"https://i.ibb.co/6bws3SG/helldivers2.png",
    },
    {
        "id":5,
        "nombre": "Minecraft Java",
        "genero":"Aventura, Exploración, Mundo Abierto",
        "desarrollador":"Mojang Studios",
        "plataformas":"PC",
        "precio": 25000,
        "foto":"https://i.ibb.co/0ZG2z6L/minecraft.png",
    },
    {
        "id":6,
        "nombre": "Grand Theft Auto 5",
        "genero":"Disparos, Exploración, Mundo Abierto",
        "desarrollador":"Rockstar Games, Rockstar North",
        "plataformas":"PC, PS3, Xbox 360, PS4, Xbox One, PS5, Xbox Series X/S",
        "precio": 30000,
        "foto":"https://i.ibb.co/bF71QRj/GTA5.png",
    },
    {
        "id":7,
        "nombre": "Deep Rock Galactic",
        "genero":"Aventura, Exploración, Disparos",
        "desarrollador":"Ghost Ship Games",
        "plataformas":"PC, PS5, PS4, Xbox One, Xbox Series X/S",
        "precio": 15000,
        "foto":"https://i.ibb.co/jbSckNh/drg.png",
    },
    {
        "id":8,
        "nombre": "POSTAL 2",
        "genero":"Disparos, Exploración, Mundo Abierto",
        "desarrollador":"Running with Scissors",
        "plataformas":"PC",
        "precio": 5000,
        "foto":"https://i.ibb.co/2Wyzn5b/postal-2.png",
    },
    {
        "id":9,
        "nombre": "Portal 2",
        "genero":"Lógica, Aventura",
        "desarrollador":"Valve",
        "plataformas":"PC, PS3, Xbox 360, Nintendo Switch",
        "precio": 10000,
        "foto":"https://i.ibb.co/HGHbF0n/portal-2.png",
    },
    {
        "id":10,
        "nombre": "Lethal Company",
        "genero":"Terror, Aventura",
        "desarrollador":"Zeekerss",
        "plataformas":"PC",
        "precio": 10000,
        "foto":"https://i.ibb.co/VCLwjXz/lethal-company.png",
    },
    {
        "id":11,
        "nombre": "Content Warning",
        "genero":"Terror, Aventura",
        "desarrollador":"Landfall Games",
        "plataformas":"PC",
        "precio": 10000,
        "foto":"https://i.ibb.co/yQccXbX/content-warning.png",
    },
    {
        "id":12,
        "nombre": "Fire Emblem: Three Houses",
        "genero":"RPG Táctico",
        "desarrollador":"Intelligent Systems",
        "plataformas":"Nintendo Switch",
        "precio": 25000,
        "foto":"https://i.ibb.co/pQy4nwr/fire-emblem.png",
    },
    {
        "id":13,
        "nombre": "Fallout 4",
        "genero":"RPG de Acción, Disparos",
        "desarrollador":"Bethesda",
        "plataformas":"PC, PS4, PS5, Xbox One, Xbox Series X/S",
        "precio": 30000,
        "foto":"https://i.ibb.co/Smmpp5r/fallout4.png",
    },
    {
        "id":14,
        "nombre": "Borderlands 2",
        "genero":"RPG de Acción, Disparos",
        "desarrollador":"Gearbox Software",
        "plataformas":"PC, PS3, PS4, Xbox 360, Xbox One, PSVita",
        "precio": 15000,
        "foto":"https://i.ibb.co/B348JjJ/borderlands2.png",
    },
    {
        "id":15,
        "nombre": "Peggle Deluxe",
        "genero":"Casual, Lógica",
        "desarrollador":"PopCap Games",
        "plataformas":"PC, PS3, Xbox 360",
        "precio": 5000,
        "foto":"https://i.ibb.co/rvhXjK3/peggle.png",
    },
    {
        "id":16,
        "nombre": "Plants vs Zombies",
        "genero":"Casual, Estrategia",
        "desarrollador":"PopCap Games",
        "plataformas":"PC, PS3, PS4, Xbox 360, Xbox One, PSVita",
        "precio": 15000,
        "foto":"https://i.ibb.co/3pdgfv3/pvz.png",
    },
    {
        "id":17,
        "nombre": "Geometry Dash",
        "genero":"Ritmo, Música",
        "desarrollador":"RobTop Games",
        "plataformas":"PC",
        "precio": 3000,
        "foto":"https://i.ibb.co/R4yB79c/gd.png",
    },
    {
        "id":18,
        "nombre": "Counter-Strike",
        "genero":"Juego de Disparos Táctico",
        "desarrollador":"Valve",
        "plataformas":"PC",
        "precio": 4000,
        "foto":"https://i.ibb.co/QjK5hLK/counter-strike.png",
    },
    {
        "id":19,
        "nombre": "Cruelty Squad",
        "genero":"Disparos, Simulación",
        "desarrollador":"Consumer Softproducts",
        "plataformas":"PC",
        "precio": 8000,
        "foto":"https://i.ibb.co/Qk2YnfC/cruelty-squad.png",
    },
    {
        "id":20,
        "nombre": "DOOM (2016)",
        "genero":"Disparos, Aventura",
        "desarrollador":"id Software",
        "plataformas":"PC, PS4, Xbox One, Nintendo Switch",
        "precio": 15000,
        "foto":"https://i.ibb.co/M9FK1VS/doom-2016.png",
    },
    {
        "id":21,
        "nombre": "DOOM Eternal",
        "genero":"Disparos, Aventura",
        "desarrollador":"id Software",
        "plataformas":"PC, PS4, PS5, Xbox One, Xbox Series X/S, Nintendo Switch",
        "precio": 25000,
        "foto":"https://i.ibb.co/x64Tn9C/doom-eternal.png",
    },
    {
        "id":22,
        "nombre": "RollerCoaster Tycoon 2",
        "genero":"Construcción, Manejo de Recursos, Simulación, Estrategia",
        "desarrollador":"Chris Sawyer",
        "plataformas":"PC",
        "precio": 2000,
        "foto":"https://i.ibb.co/QbwqHVV/rct2.png",
    },
    {
        "id":23,
        "nombre": "Red Dead Redemption 2",
        "genero":"Disparos, Acción, Aventura",
        "desarrollador":"Rockstar Games",
        "plataformas":"PC, PS4, Xbox One",
        "precio": 30000,
        "foto":"https://i.ibb.co/dmjx174/red-dead2.png",
    },
    {
        "id":24,
        "nombre": "Alan Wake 2",
        "genero":"Disparos, Terror, Acción, Aventura",
        "desarrollador":"Remedy Entertainment",
        "plataformas":"PC, PS5, Xbox Series X/S",
        "precio": 40000,
        "foto":"https://i.ibb.co/P13Z1C7/alan-wake2.png",
    },
    {
        "id":25,
        "nombre": "Half-Life 2",
        "genero":"Disparos, Acción, Aventura",
        "desarrollador":"Valve",
        "plataformas":"PC, PS3, Xbox 360, PSVita",
        "precio": 10000,
        "foto":"https://i.ibb.co/ys1WNgM/half-life2.png",
    },
    {
        "id":26,
        "nombre": "Crysis 3",
        "genero":"Disparos, Acción, Aventura",
        "desarrollador":"Crytek",
        "plataformas":"PC, PS3, Xbox 360",
        "precio": 20000,
        "foto":"https://i.ibb.co/Wpm1p3Q/crysis3.png",
    },
    {
        "id":27,
        "nombre": "Dying Light",
        "genero":"RPG, Acción, Aventura",
        "desarrollador":"Techland",
        "plataformas":"PC, PS4, Xbox One",
        "precio": 15000,
        "foto":"https://i.ibb.co/K5zH7L1/dying-light.png",
    },
];

module.exports = { jueguitos };